// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace Std
{
    namespace CompressedPair
    {
        [StructLayout(LayoutKind.Sequential, Size = 32, Pack = 8)]
        public unsafe partial struct __Internalc__N_std_S__Compressed_pair____N_std_S_allocator__C___N_std_S__String_val____N_std_S__Simple_types__C_Vb1
        {
            internal global::Std.StringVal.__Internal _Myval2;
        }
    }

    namespace Allocator
    {
        [StructLayout(LayoutKind.Sequential, Size = 1, Pack = 8)]
        public unsafe partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity, DllImport("Std-symbols", EntryPoint = "??0?$allocator@D@std@@QEAA@XZ", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern __IntPtr ctorc__N_std_S_allocator__C(__IntPtr __instance);
        }
    }

    // DEBUG: class allocator {
    // DEBUG: public:
    // DEBUG:     static_assert(!is_const_v<_Ty>, "The C++ Standard forbids containers of const elements "
    // DEBUG:                                     "because allocator<const T> is ill-formed.");
    // DEBUG: 
    // DEBUG:     using _From_primary = allocator;
    // DEBUG: 
    // DEBUG:     using value_type = _Ty;
    // DEBUG: 
    // DEBUG: #if _HAS_DEPRECATED_ALLOCATOR_MEMBERS
    // DEBUG:     using pointer _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS       = _Ty*;
    // DEBUG:     using const_pointer _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS = const _Ty*;
    // DEBUG: 
    // DEBUG:     using reference _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS       = _Ty&;
    // DEBUG:     using const_reference _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS = const _Ty&;
    // DEBUG: #endif // _HAS_DEPRECATED_ALLOCATOR_MEMBERS
    // DEBUG: 
    // DEBUG:     using size_type       = size_t;
    // DEBUG:     using difference_type = ptrdiff_t;
    // DEBUG: 
    // DEBUG:     using propagate_on_container_move_assignment           = true_type;
    // DEBUG:     using is_always_equal _CXX20_DEPRECATE_IS_ALWAYS_EQUAL = true_type;
    // DEBUG: 
    // DEBUG: #if _HAS_DEPRECATED_ALLOCATOR_MEMBERS
    // DEBUG:     template <class _Other>
    // DEBUG:     struct _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS rebind {
    // DEBUG:         using other = allocator<_Other>;
    // DEBUG:     };
    // DEBUG: 
    // DEBUG:     _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS _NODISCARD _Ty* address(_Ty& _Val) const noexcept {
    // DEBUG:         return _STD addressof(_Val);
    // DEBUG:     }
    // DEBUG: 
    // DEBUG:     _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS _NODISCARD const _Ty* address(const _Ty& _Val) const noexcept {
    // DEBUG:         return _STD addressof(_Val);
    // DEBUG:     }
    // DEBUG: #endif // _HAS_DEPRECATED_ALLOCATOR_MEMBERS
    // DEBUG: 
    // DEBUG:     constexpr allocator() noexcept {}
    // DEBUG: 
    // DEBUG:     constexpr allocator(const allocator&) noexcept = default;
    // DEBUG:     template <class _Other>
    // DEBUG:     constexpr allocator(const allocator<_Other>&) noexcept {}
    // DEBUG:     _CONSTEXPR20 ~allocator()                           = default;
    // DEBUG:     _CONSTEXPR20 allocator& operator=(const allocator&) = default;
    // DEBUG: 
    // DEBUG:     _CONSTEXPR20 void deallocate(_Ty* const _Ptr, const size_t _Count) {
    // DEBUG:         _STL_ASSERT(_Ptr != nullptr || _Count == 0, "null pointer cannot point to a block of non-zero size");
    // DEBUG:         // no overflow check on the following multiply; we assume _Allocate did that check
    // DEBUG:         _Deallocate<_New_alignof<_Ty>>(_Ptr, sizeof(_Ty) * _Count);
    // DEBUG:     }
    // DEBUG: 
    // DEBUG:     _NODISCARD_RAW_PTR_ALLOC _CONSTEXPR20 __declspec(allocator) _Ty* allocate(_CRT_GUARDOVERFLOW const size_t _Count) {
    // DEBUG:         static_assert(sizeof(value_type) > 0, "value_type must be complete before calling allocate.");
    // DEBUG:         return static_cast<_Ty*>(_Allocate<_New_alignof<_Ty>>(_Get_size_of_n<sizeof(_Ty)>(_Count)));
    // DEBUG:     }
    // DEBUG: 
    // DEBUG: #if _HAS_CXX23
    // DEBUG:     _NODISCARD_RAW_PTR_ALLOC constexpr allocation_result<_Ty*> allocate_at_least(
    // DEBUG:         _CRT_GUARDOVERFLOW const size_t _Count) {
    // DEBUG:         return {allocate(_Count), _Count};
    // DEBUG:     }
    // DEBUG: #endif // _HAS_CXX23
    // DEBUG: 
    // DEBUG: #if _HAS_DEPRECATED_ALLOCATOR_MEMBERS
    // DEBUG:     _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS _NODISCARD_RAW_PTR_ALLOC __declspec(allocator) _Ty* allocate(
    // DEBUG:         _CRT_GUARDOVERFLOW const size_t _Count, const void*) {
    // DEBUG:         return allocate(_Count);
    // DEBUG:     }
    // DEBUG: 
    // DEBUG:     template <class _Objty, class... _Types>
    // DEBUG:     _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS void construct(_Objty* const _Ptr, _Types&&... _Args) {
    // DEBUG:         ::new (_Voidify_iter(_Ptr)) _Objty(_STD forward<_Types>(_Args)...);
    // DEBUG:     }
    // DEBUG: 
    // DEBUG:     template <class _Uty>
    // DEBUG:     _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS void destroy(_Uty* const _Ptr) {
    // DEBUG:         _Ptr->~_Uty();
    // DEBUG:     }
    // DEBUG: 
    // DEBUG:     _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS _NODISCARD size_t max_size() const noexcept {
    // DEBUG:         return static_cast<size_t>(-1) / sizeof(_Ty);
    // DEBUG:     }
    // DEBUG: #endif // _HAS_DEPRECATED_ALLOCATOR_MEMBERS
    // DEBUG: 
    // DEBUG:     static constexpr size_t _Minimum_allocation_alignment = _Asan_granularity;
    // DEBUG: }
    public unsafe partial class Allocator<_Ty> : IDisposable
    {
        public __IntPtr __Instance { get; protected set; }

        internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Std.Allocator<_Ty>> NativeToManagedMap =
            new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Std.Allocator<_Ty>>();

        internal static void __RecordNativeToManagedMapping(IntPtr native, global::Std.Allocator<_Ty> managed)
        {
            NativeToManagedMap[native] = managed;
        }

        internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::Std.Allocator<_Ty> managed)
        {
    
            return NativeToManagedMap.TryGetValue(native, out managed);
        }

        protected bool __ownsNativeInstance;

        internal static Allocator<_Ty> __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            return new Allocator<_Ty>(native.ToPointer(), skipVTables);
        }

        internal static Allocator<_Ty> __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (__TryGetNativeToManagedMapping(native, out var managed))
                return (Allocator<_Ty>)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                __RecordNativeToManagedMapping(native, result);
            return result;
        }

        internal static Allocator<_Ty> __CreateInstance(global::Std.Allocator.__Internal native, bool skipVTables = false)
        {
            return new Allocator<_Ty>(native, skipVTables);
        }

        private static void* __CopyValue(global::Std.Allocator.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Std.Allocator.__Internal));
            *(global::Std.Allocator.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private Allocator(global::Std.Allocator.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
        }

        protected Allocator(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        // DEBUG: constexpr allocator() noexcept {}
        public Allocator()
        {
            var ___Ty = typeof(_Ty);
            if (___Ty.IsAssignableFrom(typeof(char)))
            {
                __Instance = Marshal.AllocHGlobal(sizeof(global::Std.Allocator.__Internal));
                __ownsNativeInstance = true;
                __RecordNativeToManagedMapping(__Instance, this);
                global::Std.Allocator.__Internal.ctorc__N_std_S_allocator__C(__Instance);
                return;
            }
            throw new ArgumentOutOfRangeException("_Ty", string.Join(", ", new[] { typeof(_Ty).FullName }), "global::Std.Allocator<_Ty> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <char>.");
        }

        public void Dispose()
        {
            Dispose(disposing: true, callNativeDtor : __ownsNativeInstance );
        }

        partial void DisposePartial(bool disposing);

        internal protected virtual void Dispose(bool disposing, bool callNativeDtor )
        {
            if (__Instance == IntPtr.Zero)
                return;
            NativeToManagedMap.TryRemove(__Instance, out _);
            DisposePartial(disposing);
            if (callNativeDtor)
            {
                var ___Ty = typeof(_Ty);
                if (___Ty.IsAssignableFrom(typeof(char)))
                {
                    return;
                }
                throw new ArgumentOutOfRangeException("_Ty", string.Join(", ", new[] { typeof(_Ty).FullName }), "global::Std.Allocator<_Ty> maps a C++ template class and therefore it only supports a limited set of types and their subclasses: <char>.");
            }
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }
    }
}

namespace Std
{
}

namespace Std
{
    namespace StringVal
    {
        [StructLayout(LayoutKind.Sequential, Size = 32, Pack = 8)]
        public unsafe partial struct __Internal
        {
            internal global::Std.StringVal.Bxty.__Internal _Bx;
            internal ulong _Mysize;
            internal ulong _Myres;
        }

        namespace Bxty
        {
            [StructLayout(LayoutKind.Explicit, Size = 16, Pack = 8)]
            public unsafe partial struct __Internal
            {
                [FieldOffset(0)]
                internal fixed sbyte _Buf[16];

                [FieldOffset(0)]
                internal __IntPtr _Ptr;

                [FieldOffset(0)]
                internal fixed sbyte _Alias[16];
            }
        }

    }

    namespace CharTraits
    {
        [StructLayout(LayoutKind.Sequential, Size = 1, Pack = 8)]
        public unsafe partial struct __Internal
        {
        }
    }

    // DEBUG: struct char_traits : _Char_traits<_Elem, long> {}
    public unsafe partial class CharTraits<_Elem> : IDisposable
    {
        public __IntPtr __Instance { get; protected set; }

        internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Std.CharTraits<_Elem>> NativeToManagedMap =
            new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Std.CharTraits<_Elem>>();

        internal static void __RecordNativeToManagedMapping(IntPtr native, global::Std.CharTraits<_Elem> managed)
        {
            NativeToManagedMap[native] = managed;
        }

        internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::Std.CharTraits<_Elem> managed)
        {
    
            return NativeToManagedMap.TryGetValue(native, out managed);
        }

        protected bool __ownsNativeInstance;

        internal static CharTraits<_Elem> __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            return new CharTraits<_Elem>(native.ToPointer(), skipVTables);
        }

        internal static CharTraits<_Elem> __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (__TryGetNativeToManagedMapping(native, out var managed))
                return (CharTraits<_Elem>)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                __RecordNativeToManagedMapping(native, result);
            return result;
        }

        internal static CharTraits<_Elem> __CreateInstance(global::Std.CharTraits.__Internal native, bool skipVTables = false)
        {
            return new CharTraits<_Elem>(native, skipVTables);
        }

        private static void* __CopyValue(global::Std.CharTraits.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Std.CharTraits.__Internal));
            *(global::Std.CharTraits.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private CharTraits(global::Std.CharTraits.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
        }

        protected CharTraits(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        public void Dispose()
        {
            Dispose(disposing: true, callNativeDtor : __ownsNativeInstance );
        }

        partial void DisposePartial(bool disposing);

        internal protected virtual void Dispose(bool disposing, bool callNativeDtor )
        {
            if (__Instance == IntPtr.Zero)
                return;
            NativeToManagedMap.TryRemove(__Instance, out _);
            DisposePartial(disposing);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }
    }
}
